# Generated by Django 5.2.4 on 2025-07-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_extracted_text_field'),
        ('notes', '0002_studymaterial_chapter_name_studymaterial_semester_and_more'),
    ]

    operations = [
    ]
